/* ./src/include/config.h
 * Defines created automatically for configuration script
 * Copyright (c) 2001 Alien Internet Services
 *
 * DO NOT EDIT THIS FILE! IT IS GENERATED AUTOMATICALLY!! :)
 *
 */

#ifndef __CONFIG_H_
# define __CONFIG_H_

/* WARNING!
 * 
 * These settings should NOT be changed unless you really know what you are
 * doing. They may conform to standards, or have limits you may or may not be
 * unaware of.
 * 
 * When changing settings in here, just to be safe make sure you do a 
 * 'make clean' then remake the package to avoid code discrepancies.
 */

/* Define if you want to compile an on-line debug ready version */
# define DEBUG

/******************************************************************************
**                                                                           **
**                  WARNING!   WARNING!   WARNING!   WARNING!                **
**                                                                           **
**   Do not change anything below this line - These settings are generated   **
**   _AUTOMATICALLY_ by the configuration script and reflect the settings    **
**   required to allow this software to compile on your system. You should   **
**     only edit the below lines if you know what you are doing, and this    **
**        package is not compiling for you due to an incorrect define.       **
**                                                                           **
******************************************************************************/

# ifndef HAVE_CONFIG_H
#  error "You must run configure before compiling this software"  
# endif
@TOP@

/* Define it the C++ compiler has STL (Standard Template Library) support */
#undef HAVE_CXX_STL

/* Define if signal() has a third variable (struct sigcontext *) */
#undef HAVE_STRUCT_SIGCONTEXT

/* Define if the signal SIGCHLD is broken */
#undef SIGCHLD_BRAIN_DAMAGE

@BOTTOM@


#endif
