/* src/include/config.h.  Generated automatically by configure.  */
/* src/include/config.h.in.  Generated automatically from configure.in by autoheader.  */
/* ./src/include/config.h
 * Defines created automatically for configuration script
 * Copyright (c) 2001 Alien Internet Services
 *
 * DO NOT EDIT THIS FILE! IT IS GENERATED AUTOMATICALLY!! :)
 *
 */

#ifndef __CONFIG_H_
# define __CONFIG_H_

/* WARNING!
 * 
 * These settings should NOT be changed unless you really know what you are
 * doing. They may conform to standards, or have limits you may or may not be
 * unaware of.
 * 
 * When changing settings in here, just to be safe make sure you do a 
 * 'make clean' then remake the package to avoid code discrepancies.
 */

/* Define if you want to compile an on-line debug ready version */
# define DEBUG

/******************************************************************************
**                                                                           **
**                  WARNING!   WARNING!   WARNING!   WARNING!                **
**                                                                           **
**   Do not change anything below this line - These settings are generated   **
**   _AUTOMATICALLY_ by the configuration script and reflect the settings    **
**   required to allow this software to compile on your system. You should   **
**     only edit the below lines if you know what you are doing, and this    **
**        package is not compiling for you due to an incorrect define.       **
**                                                                           **
******************************************************************************/

# ifndef HAVE_CONFIG_H
#  error "You must run configure before compiling this software"  
# endif

/* Define if type char is unsigned and you are not using gcc.  */
#ifndef __CHAR_UNSIGNED__
/* #undef __CHAR_UNSIGNED__ */
#endif

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define if the `long double' type works.  */
#define HAVE_LONG_DOUBLE 1

/* Define if you have <sys/wait.h> that is POSIX.1 compatible.  */
#define HAVE_SYS_WAIT_H 1

/* Define if your struct tm has tm_zone.  */
#define HAVE_TM_ZONE 1

/* Define if you don't have tm_zone but do have the external array
   tzname.  */
/* #undef HAVE_TZNAME */

/* Define as __inline if that's what the C compiler calls it.  */
/* #undef inline */

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef mode_t */

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef pid_t */

/* Define as the return type of signal handlers (int or void).  */
#define RETSIGTYPE void

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define if the `S_IS*' macros in <sys/stat.h> do not work properly.  */
/* #undef STAT_MACROS_BROKEN */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if `sys_siglist' is declared by <signal.h>.  */
#define SYS_SIGLIST_DECLARED 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define if your <sys/time.h> declares struct tm.  */
/* #undef TM_IN_SYS_TIME */

/* Define if your processor stores words with the most significant
   byte first (like Motorola and SPARC, unlike Intel and VAX).  */
/* #undef WORDS_BIGENDIAN */

/* Define it the C++ compiler has STL (Standard Template Library) support */
#define HAVE_CXX_STL 1

/* Define if signal() has a third variable (struct sigcontext *) */
#define HAVE_STRUCT_SIGCONTEXT 1

/* Define if the signal SIGCHLD is broken */
/* #undef SIGCHLD_BRAIN_DAMAGE */

/* Define if you have the memcpy function.  */
#define HAVE_MEMCPY 1

/* Define if you have the select function.  */
#define HAVE_SELECT 1

/* Define if you have the socket function.  */
#define HAVE_SOCKET 1

/* Define if you have the <dirent.h> header file.  */
#define HAVE_DIRENT_H 1

/* Define if you have the <fcntl.h> header file.  */
#define HAVE_FCNTL_H 1

/* Define if you have the <math.h> header file.  */
#define HAVE_MATH_H 1

/* Define if you have the <memory.h> header file.  */
#define HAVE_MEMORY_H 1

/* Define if you have the <ndir.h> header file.  */
/* #undef HAVE_NDIR_H */

/* Define if you have the <sys/dir.h> header file.  */
/* #undef HAVE_SYS_DIR_H */

/* Define if you have the <sys/ndir.h> header file.  */
/* #undef HAVE_SYS_NDIR_H */

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1


#endif
